In [5]:
import pandas as pd
import numpy as np

In [6]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in c:\users\rishabh mishra\miniconda3\lib\site-packages (5.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (4.56.2)
Requirement already satisfied: tqdm in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (2.8.0)
Requirement already satisfied: scikit-learn in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (0.35.0)
Requirement already satisfied: Pillow in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (11.1.0)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sentence_transformers) (4.12.2)
Requirement already satisfied: filelock in c:\users\rishabh mishra\miniconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.9.0)
Requirement already satisfied: packaging>=20.9 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.2)
Requirement already satisfied: requests in c:\users\rishabh mishra\miniconda3\lib\site-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2.32.3)
Requirement already satisfied: sympy>=1.13.3 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from torch>=1.11.0->sentence_transformers) (1.14.0)
Requirement already satisfied: networkx in c:\users\rishabh mishra\miniconda3\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.5)
Requirement already satisfied: jinja2 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\rishabh mishra\miniconda3\lib\site-packages (from torch>=1.11.0->sentence_transformers) (78.1.1)
Requirement already satisfied: colorama in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tqdm->sentence_transformers) (0.4.6)
Requirement already satisfied: numpy>=1.17 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.2.5)
Requirement already satisfied: regex!=2019.12.17 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from scikit-learn->sentence_transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2025.4.26)

In [7]:
!pip install tf-keras

Requirement already satisfied: tf-keras in c:\users\rishabh mishra\miniconda3\lib\site-packages (2.20.1)
Requirement already satisfied: tensorflow<2.21,>=2.20 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tf-keras) (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.4.0)
Requirement already satisfied: packaging in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (6.31.1)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.32.3)
Requirement already satisfied: setuptools in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (78.1.1)
Requirement already satisfied: six>=1.12.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (1.73.1)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.11.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (2.2.5)
Requirement already satisfied: h5py>=3.11.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorflow<2.21,>=2.20->tf-keras) (0.5.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.21,>=2.20->tf-keras) (0.45.1)
Requirement already satisfied: rich in c:\users\rishabh mishra\miniconda3\lib\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (13.9.4)
Requirement already satisfied: namex in c:\users\rishabh mishra\miniconda3\lib\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.1.0)
Requirement already satisfied: optree in c:\users\rishabh mishra\miniconda3\lib\site-packages (from keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow<2.21,>=2.20->tf-keras) (2025.4.26)
Requirement already satisfied: markdown>=2.6.8 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.8.2)
Requirement already satisfied: pillow in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (11.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow<2.21,>=2.20->tf-keras) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow<2.21,>=2.20->tf-keras) (0.1.0)

In [8]:
from sentence_transformers import SentenceTransformer, util

In [9]:
df=pd.read_csv("train.csv")

df=df.dropna()


df= df.sample(frac=0.10, random_state=42) 

df.head()
# df.shape[0]


df_t=pd.read_csv("test.csv")
df_t=df_t.dropna()


cat_path=df['category_path']

org_qr=df['origin_query']
print(df.shape[0])
print(df_t.shape[0])

2131
1184

In [10]:
df.head()
# df.isna().sum()

,task,language,origin_query,category_path,label
15449,QC,it,carplay moto,"motorcycle equipments & parts,motorcycle acces...",1
10782,QC,de,kpop Schlüsselanhänger,"jewelry & accessories,fashion jewelry,key chains",1
9933,QC,ko,일본 남자,"novelty & special use,world apparel,traditiona...",0
6825,QC,es,protector de tarjeta,"office & school supplies,desk accessories & or...",0
14031,QC,it,qqlt,"apparel accessories,eyewear & accessories,sung...",0

In [11]:
cat_path = cat_path.apply(lambda x: x.split(",") if pd.notna(x) else [])

In [12]:
cat_path.dtype

dtype('O')

In [13]:
model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [14]:

from sentence_transformers import SentenceTransformer, util
import numpy as np

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

def calculate_product_score(product_name, tags, model=model):
    if not isinstance(product_name, str) or not tags or len(tags) == 0:
        return np.nan
    product_embedding = model.encode(product_name, convert_to_tensor=True)
    tag_embeddings = model.encode(tags, convert_to_tensor=True)
    similarities = [util.cos_sim(product_embedding, tag_emb)[0].item() for tag_emb in tag_embeddings]
    # Compute weights: 1, 0.5, 0.25, ...
    weights = [0.4** i for i in range(len(similarities))]
    weighted_mean = np.average(similarities, weights=weights)
    return weighted_mean

# Apply function row-wise
# df['Score'] = df.apply(lambda row: calculate_product_score(row['origin_query'], row['category_path']), axis=1)

In [15]:
# df['Score'] = df.apply(lambda row: calculate_product_score(row['origin_query'], row['category_path']), axis=1)
print(calculate_product_score("Shirt",["Clothing","Apparel","Cotton"]))
# print(calculate_product_score("Shirt",["Shirt","Apparel","Cotton"]))
df['score'] = [calculate_product_score(name, tags) for name, tags in zip(org_qr.values, cat_path.values)]

0.557737145668421

In [16]:
df.head()

,task,language,origin_query,category_path,label,score
15449,QC,it,carplay moto,"motorcycle equipments & parts,motorcycle acces...",1,0.574312
10782,QC,de,kpop Schlüsselanhänger,"jewelry & accessories,fashion jewelry,key chains",1,0.403361
9933,QC,ko,일본 남자,"novelty & special use,world apparel,traditiona...",0,0.271373
6825,QC,es,protector de tarjeta,"office & school supplies,desk accessories & or...",0,0.210521
14031,QC,it,qqlt,"apparel accessories,eyewear & accessories,sung...",0,0.285094

In [17]:
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import confusion_matrix
df['result']=[0 if scr<0.20 else 1 for scr in df['score']]
df.head()

f1_sc=f1_score(df['label'],df['result'])

df['true'] = [1 if lbl == rslt else 0 for lbl, rslt in zip(df['label'].values, df['result'].values)]
df.head()
df['true'].sum()


# Precision
precision = precision_score(df['label'], df['result'])
print("Precision:", precision)

# Recall
recall = recall_score(df['label'], df['result'])
print("Recall:", recall)
cm = confusion_matrix(df['label'], df['result'])
print(cm)
print(f1_sc)

print(df['true'].sum())


from sklearn.metrics import classification_report

print(classification_report(df['label'],df['result']))

Precision: 0.6853348729792148
Recall: 0.8266016713091922
[[ 150  545]
 [ 249 1187]]
0.7493686868686869
1337
              precision    recall  f1-score   support

           0       0.38      0.22      0.27       695
           1       0.69      0.83      0.75      1436

    accuracy                           0.63      2131
   macro avg       0.53      0.52      0.51      2131
weighted avg       0.58      0.63      0.59      2131